sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  global:
    - PATH="$TRAVIS_BUILD_DIR/vendor/bin:$PATH"
    - WP_CLI_BIN_DIR="$TRAVIS_BUILD_DIR/vendor/bin"

matrix:
  include:
    - php: 7.1
      env: WP_VERSION=latest

before_install:
  - |
    # Remove Xdebug for a huge performance increase:
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi

install:
  - composer require wp-cli/wp-cli:dev-master
  - composer require wp-cli/core-command:dev-master
  - composer require wp-cli/config-command:dev-master
  - composer require wp-cli/db-command:dev-master
  - composer require wp-cli/entity-command:dev-master
  - composer require wp-cli/eval-command:dev-master
  - composer require wp-cli/extension-command:dev-master
  - composer require wp-cli/media-command:dev-master
  - composer require wp-cli/search-replace-command:dev-master
  - composer update
  - composer install
  - bash bin/install-package-tests.sh

before_script:
  - composer validate

script:
  - bash bin/test.sh
